In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [5]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [6]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [7]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [8]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.random.randint(10)

9

In [11]:
np.random.randn(10)

array([ 1.07230054, -0.11689564,  1.44049131, -1.13632383, -1.39703235,
        1.40592927,  0.87713523, -0.08915691,  0.21770728, -0.41458221])

In [12]:
np.random.rand(10)

array([0.151889  , 0.25531019, 0.70693291, 0.32042571, 0.40384906,
       0.22993842, 0.49681843, 0.78046199, 0.85916968, 0.82589079])

In [13]:
np.linspace(0,1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [14]:
np.linspace(0.01,10,100)

array([ 0.01      ,  0.11090909,  0.21181818,  0.31272727,  0.41363636,
        0.51454545,  0.61545455,  0.71636364,  0.81727273,  0.91818182,
        1.01909091,  1.12      ,  1.22090909,  1.32181818,  1.42272727,
        1.52363636,  1.62454545,  1.72545455,  1.82636364,  1.92727273,
        2.02818182,  2.12909091,  2.23      ,  2.33090909,  2.43181818,
        2.53272727,  2.63363636,  2.73454545,  2.83545455,  2.93636364,
        3.03727273,  3.13818182,  3.23909091,  3.34      ,  3.44090909,
        3.54181818,  3.64272727,  3.74363636,  3.84454545,  3.94545455,
        4.04636364,  4.14727273,  4.24818182,  4.34909091,  4.45      ,
        4.55090909,  4.65181818,  4.75272727,  4.85363636,  4.95454545,
        5.05545455,  5.15636364,  5.25727273,  5.35818182,  5.45909091,
        5.56      ,  5.66090909,  5.76181818,  5.86272727,  5.96363636,
        6.06454545,  6.16545455,  6.26636364,  6.36727273,  6.46818182,
        6.56909091,  6.67      ,  6.77090909,  6.87181818,  6.97

In [15]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [16]:
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [96]:
ar=np.arange(1,26).reshape(5,5)
ar
ar[1:4,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [18]:
ar=np.arange(1,26).reshape(5,5)
print(ar)

print()
print()
print(ar[1:4,2:5])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [19]:
ar=np.arange(1,26).reshape(5,5)
ar[2:5,0:3]

array([[11, 12, 13],
       [16, 17, 18],
       [21, 22, 23]])

In [20]:
ar

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [21]:
mat=np.arange(1,26).reshape(5,5)

mat[2:5,1:4]

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [22]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [23]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [24]:
mat[4:]

array([[21, 22, 23, 24, 25]])

In [25]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [26]:
mat[:-2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [27]:
mat[-2:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [28]:
#sum of all digits:
np.sum(mat)

325

In [29]:
#standard deviation:
np.std(mat)

7.211102550927978

In [30]:
#sum of all columns:
print(np.sum(mat,axis=1))
print(mat)

[ 15  40  65  90 115]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [31]:
leo=np.arange(1,11)
leo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
leo=np.arange(0,12).reshape(3,4)
leo

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
leo=np.arange(0,27).reshape(3,3,3)
leo

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [34]:
leo.dtype

dtype('int64')

In [35]:
leo.shape


(3, 3, 3)

In [36]:
np.ones(20).reshape(4,5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
a=np.random.randint(1,100,20)
a

array([72, 30, 58, 53, 31, 68, 29, 46, 10, 45, 63, 55, 50, 21, 35, 24, 15,
       38, 84, 43])

In [38]:
b=np.sort(a)
b

array([10, 15, 21, 24, 29, 30, 31, 35, 38, 43, 45, 46, 50, 53, 55, 58, 63,
       68, 72, 84])

In [39]:
y = np.copy(a)

In [40]:
np.sort??

In [41]:
np.flip(b)

array([84, 72, 68, 63, 58, 55, 53, 50, 46, 45, 43, 38, 35, 31, 30, 29, 24,
       21, 15, 10])

In [42]:
np.copy??

In [43]:
p=np.eye(5)

In [44]:
p

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
o=np.arange(0,25).reshape(5,5)
o

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
o.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [47]:
o.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [48]:

o=np.append(mat,[[25],[26],[27],[28],[29]],axis=1)
o

array([[ 1,  2,  3,  4,  5, 25],
       [ 6,  7,  8,  9, 10, 26],
       [11, 12, 13, 14, 15, 27],
       [16, 17, 18, 19, 20, 28],
       [21, 22, 23, 24, 25, 29]])

In [49]:
o=np.append(mat,[[25,26,27,28,29]],axis=0)
o

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [25, 26, 27, 28, 29]])

In [50]:
np.vsplit(mat,5)

[array([[1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15]]),
 array([[16, 17, 18, 19, 20]]),
 array([[21, 22, 23, 24, 25]])]

In [51]:
print(np.vsplit(mat,5))
print("\n",np.hsplit(mat,5))

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15]]), array([[16, 17, 18, 19, 20]]), array([[21, 22, 23, 24, 25]])]

 [array([[ 1],
       [ 6],
       [11],
       [16],
       [21]]), array([[ 2],
       [ 7],
       [12],
       [17],
       [22]]), array([[ 3],
       [ 8],
       [13],
       [18],
       [23]]), array([[ 4],
       [ 9],
       [14],
       [19],
       [24]]), array([[ 5],
       [10],
       [15],
       [20],
       [25]])]


In [52]:
r=np.eye(4)+4
r

array([[5., 4., 4., 4.],
       [4., 5., 4., 4.],
       [4., 4., 5., 4.],
       [4., 4., 4., 5.]])

In [53]:
t=np.zeros(81).reshape(9,9)
t

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [54]:
#To find Floating random numbers value:
rarr=np.random.uniform(0,15,10)
rarr


array([ 2.403148  ,  9.08120449,  3.44794157,  1.79254002, 11.27010703,
       12.94087707,  3.65708732,  4.663545  ,  6.47867956,  8.25148975])

In [55]:
i=np.sort(rarr)
i=np.flip(i)
print(i)
np.round(i,decimals=2)

[12.94087707 11.27010703  9.08120449  8.25148975  6.47867956  4.663545
  3.65708732  3.44794157  2.403148    1.79254002]


array([12.94, 11.27,  9.08,  8.25,  6.48,  4.66,  3.66,  3.45,  2.4 ,
        1.79])

In [56]:
np.ceil(rarr)

array([ 3., 10.,  4.,  2., 12., 13.,  4.,  5.,  7.,  9.])

In [57]:
np.floor(rarr)

array([ 2.,  9.,  3.,  1., 11., 12.,  3.,  4.,  6.,  8.])

In [58]:
ra= np.arange(0,25).reshape(5,5)
ra

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [59]:
print(ra)
print()
print(np.sum(ra))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

300


In [60]:
print(ra)
print()
print(np.min(ra))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

0


In [61]:
print(ra)
print()
print(np.std(ra,axis=0))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[7.07106781 7.07106781 7.07106781 7.07106781 7.07106781]


In [62]:
print(ra)
print()
print(np.max(ra))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

24


In [63]:
print(ra)
print()
print(np.var(ra))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

52.0


In [64]:
null=np.full(10,'Nan')
null
null[5]=200
null

array(['Nan', 'Nan', 'Nan', 'Nan', 'Nan', '200', 'Nan', 'Nan', 'Nan',
       'Nan'], dtype='<U3')

In [65]:
rev= np.arange(100,151)
rev

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [66]:
np.flip(rev)

array([150, 149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138,
       137, 136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125,
       124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112,
       111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

In [67]:
 np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [68]:
#Locate non-zero value:

np.nonzero([1,0,2,0,0,4,0,8])

(array([0, 2, 5, 7]),)

In [69]:
#Create box structure:

box=np.zeros(100).reshape(10,10)

box[::2,::2]=1
box[1::2,1::2]=1
box

array([[1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]])

In [70]:
j=box
j[0::3,0::3]="Nan"
print(j)

print()
h=box
h[:,0::2]=4

print(h)

[[nan  0.  1. nan  1.  0. nan  0.  1. nan]
 [ 0.  1.  0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.  1.  0.]
 [nan  1.  0. nan  0.  1. nan  1.  0. nan]
 [ 1.  0.  1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.  0.  1.]
 [nan  0.  1. nan  1.  0. nan  0.  1. nan]
 [ 0.  1.  0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.  1.  0.]
 [nan  1.  0. nan  0.  1. nan  1.  0. nan]]

[[ 4.  0.  4. nan  4.  0.  4.  0.  4. nan]
 [ 4.  1.  4.  1.  4.  1.  4.  1.  4.  1.]
 [ 4.  0.  4.  0.  4.  0.  4.  0.  4.  0.]
 [ 4.  1.  4. nan  4.  1.  4.  1.  4. nan]
 [ 4.  0.  4.  0.  4.  0.  4.  0.  4.  0.]
 [ 4.  1.  4.  1.  4.  1.  4.  1.  4.  1.]
 [ 4.  0.  4. nan  4.  0.  4.  0.  4. nan]
 [ 4.  1.  4.  1.  4.  1.  4.  1.  4.  1.]
 [ 4.  0.  4.  0.  4.  0.  4.  0.  4.  0.]
 [ 4.  1.  4. nan  4.  1.  4.  1.  4. nan]]


In [71]:
chess=np.ones(64).reshape(8,8)
chess

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [72]:
chess[::2,::2]=0
chess[1::2,1::2]=0
chess

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [73]:
"mat multi ke liye @ use karo"

'mat multi ke liye @ use karo'

In [74]:
mat1=np.random.randint(1,30,(3,3))
mat2=np.random.randint(1,24,(3,3))
print(mat1)
print()
print()
print(mat2)

[[16 12 28]
 [29  4 20]
 [ 4 23  7]]


[[ 4  5 15]
 [ 4 10 18]
 [ 6 13 17]]


In [75]:
# Addition
mat1+mat2

array([[20, 17, 43],
       [33, 14, 38],
       [10, 36, 24]])

In [76]:
# Subtraction
mat1-mat2

array([[ 12,   7,  13],
       [ 25,  -6,   2],
       [ -2,  10, -10]])

In [77]:
# Matrix multiplication 
mat1@mat2 

array([[280, 564, 932],
       [252, 445, 847],
       [150, 341, 593]])

In [78]:
#Normal multiplication
mat1*mat2

array([[ 64,  60, 420],
       [116,  40, 360],
       [ 24, 299, 119]])

In [79]:
# [Start:Stop:Step]
# SPLIT
split=np.ones(64).reshape(8,8)
split[0:8:2,0:8:2]=0
split [1:8:2,1:8:2]=0
split

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [80]:
o

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [25, 26, 27, 28, 29]])

In [81]:
np.nonzero([1,2,3,3,4,5,7,0,0,0,0,0])

(array([0, 1, 2, 3, 4, 5, 6]),)

In [82]:
o?


In [83]:
x=np.zeros(64).reshape(8,8)
x[0:8:2,0:8:2]=1
x[1:8:2,1:8:2]=1

x

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [84]:
y=np.ones(81).reshape(9,9)
y[::2,::2]=0
y[1::2,1::2]=0

y

array([[0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0.]])

In [85]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [86]:
class pratham:
    def __init__(self,name,age):
        self.name=name
        self.age=age
    
obj=pratham('Pratham J','20')
print(obj.name)
print(obj.age)

class vansh(pratham):

    obj=pratham('Vansh','20')
    print('\n')
    print(obj.name)
    print(obj.age)

Pratham J
20


Vansh
20
